export const GET_USER_LIST_SAGA = 'GET_USER_LIST_SAGA';
export const GET_USER_LIST_START = 'GET_USER_LIST_START';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAIL = 'GET_USER_LIST_FAIL';
